version: "3"
services:
  article_processing:
    build: .
    image: article_processing
  article_processing_web:
    image: article_processing
    container_name: article_processing_web
    command: "apps/web_app.py"
    ports:
      - "8511:80"
    restart: on-failure
  article_processing_streamlit_lite:
    image: article_processing
    container_name: article_processing_streamlit_lite
    command: "apps/streamlit_app_lite.py"
    ports:
      - "8512:8501"
    restart: on-failure
    depends_on:
      - article_processing_web
  article_processing_streamlit:
    image: article_processing
    container_name: article_processing_streamlit
    command: "apps/streamlit_app.py"
    ports:
      - "8513:8501"
    restart: on-failure
