services:
  article_processing:
    build: .
    image: article_processing
  api:
    image: article_processing
    container_name: article_processing_api
    command: "run.py api_app"
    ports:
      - "8511:80"
    restart: on-failure
  streamlit_with_api:
    image: article_processing
    container_name: article_processing_streamlit_lite
    command: "run.py streamlit_app_lite"
    ports:
      - "8512:8501"
    restart: on-failure
    depends_on:
      - api
  streamlit:
    image: article_processing
    container_name: article_processing_streamlit
    command: "run.py streamlit_app"
    ports:
      - "8513:8501"
    restart: on-failure
